
[profile.default]
solc_version = '0.8.15'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200 # Default amount
ffi = true
fuzz_runs = 1_000
remappings = [
  "forge-std=lib/forge-std/src/",
  "foundry-huff=lib/foundry-huff/src/",
]

# ignore solc warnings
# 1878 missing license
# 9302 unused low level return call
# 5667 unused function parameter
# 2519 shawdowing
ignored_error_codes = [1878, 9302, 5667, 2519]

